language: crystal
services:
  - docker
  env:
    global:
    - PGPORT=5433  
install:
  - shards install
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - crystal spec
  - bin/ameba
