language: crystal

services:
  - docker 

install:
  - docker pull gabfitzgerald/hello-place
  - docker run -d -p 2222:22 gabfitzgerald/hello-place
  - docker run -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres
  - shards install

script:
  - crystal spec
  - bin/ameba
