language: crystal

services:
  - docker 

install:
  - docker pull gabfitzgerald/hello-place
  - docker run -d -p 2222:22 -e ROOT_PASS="PASSWORD" gabfitzgerald/hello-place
  - shards install

script:
  - crystal spec
  - bin/ameba
