language: crystal

service:
  - docker

install:
  - docker run --net="host" -p 5432:5432 -e POSTGRES_USER=gab -e POSTGRES_PASSWORD=postgres -d postgres
  - shards install
  
script:
  - crystal spec
  - bin/ameba
