language: crystal

service:
  - docker

install:
  # - docker run --net="host" -p 5432:5432 -e POSTGRES_USER=gab -e POSTGRES_PASSWORD=postgres -d postgres
  - shards install
  
 

script:
  - crystal spec
  - bin/ameba
  - ENV_VAR=test docker-compose up --build --exit-code-from web
